### ISSUE TITLE
ci: `upload-tarball` action "broken" after removal of `prep-release` action

### ISSUE THREAD

**Issue by cmoussa1** [flux-framework/flux-accounting#380]
Looks like I wasn't paying close enough attention when I removed the `prep-release` action when I landed #375 yesterday. A `.tar.gz` file was still uploaded successfully when I tagged and released flux-accounting `v0.27.0`, but the `upload-tarball` action failed because it could not find `asset_path` and `asset_name`, both of which I _believe_ take information from the `prep-release` action:

```yaml
    - name: upload tarball
      id: upload-tarball
      if: success() && matrix.create_release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ steps.prep_release.outputs.tarball }}
        asset_name: ${{ steps.prep_release.outputs.tarball }}
        asset_content_type: "application/gzip"
```

Can I just change those to `steps.create_release.*` instead of `steps.prep_release.*`? Do you have any thoughts or suggestions @grondo?
